//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ArcSpeedCalculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MioGraph;

/** @hidden */
public class _SpeedCalculatorMasterPrxI extends com.zeroc.Ice._ObjectPrxI implements SpeedCalculatorMasterPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
