//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ArcSpeedCalculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MioGraph;

/**
 * Helper class for marshaling/unmarshaling ArcSpeedSeq.
 **/
public final class ArcSpeedSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, ArcSpeed[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                ArcSpeed.ice_write(ostr, v[i0]);
            }
        }
    }

    public static ArcSpeed[] read(com.zeroc.Ice.InputStream istr)
    {
        final ArcSpeed[] v;
        final int len0 = istr.readAndCheckSeqSize(36);
        v = new ArcSpeed[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = ArcSpeed.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ArcSpeed[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, ArcSpeed[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            final int optSize = v == null ? 0 : v.length;
            ostr.writeSize(optSize > 254 ? optSize * 36 + 5 : optSize * 36 + 1);
            ArcSpeedSeqHelper.write(ostr, v);
        }
    }

    public static java.util.Optional<ArcSpeed[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            ArcSpeed[] v;
            v = ArcSpeedSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
