//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ArcSpeedCalculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MioGraph;

public class ArcSpeed implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public int fromStopId;

    public int toStopId;

    public int routeId;

    public int orientation;

    public double averageSpeed;

    public int sampleCount;

    public long processingTimeMs;

    public ArcSpeed()
    {
    }

    public ArcSpeed(int fromStopId, int toStopId, int routeId, int orientation, double averageSpeed, int sampleCount, long processingTimeMs)
    {
        this.fromStopId = fromStopId;
        this.toStopId = toStopId;
        this.routeId = routeId;
        this.orientation = orientation;
        this.averageSpeed = averageSpeed;
        this.sampleCount = sampleCount;
        this.processingTimeMs = processingTimeMs;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ArcSpeed r = null;
        if(rhs instanceof ArcSpeed)
        {
            r = (ArcSpeed)rhs;
        }

        if(r != null)
        {
            if(this.fromStopId != r.fromStopId)
            {
                return false;
            }
            if(this.toStopId != r.toStopId)
            {
                return false;
            }
            if(this.routeId != r.routeId)
            {
                return false;
            }
            if(this.orientation != r.orientation)
            {
                return false;
            }
            if(this.averageSpeed != r.averageSpeed)
            {
                return false;
            }
            if(this.sampleCount != r.sampleCount)
            {
                return false;
            }
            if(this.processingTimeMs != r.processingTimeMs)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::MioGraph::ArcSpeed");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fromStopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, toStopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, routeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, orientation);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, averageSpeed);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sampleCount);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, processingTimeMs);
        return h_;
    }

    public ArcSpeed clone()
    {
        ArcSpeed c = null;
        try
        {
            c = (ArcSpeed)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.fromStopId);
        ostr.writeInt(this.toStopId);
        ostr.writeInt(this.routeId);
        ostr.writeInt(this.orientation);
        ostr.writeDouble(this.averageSpeed);
        ostr.writeInt(this.sampleCount);
        ostr.writeLong(this.processingTimeMs);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.fromStopId = istr.readInt();
        this.toStopId = istr.readInt();
        this.routeId = istr.readInt();
        this.orientation = istr.readInt();
        this.averageSpeed = istr.readDouble();
        this.sampleCount = istr.readInt();
        this.processingTimeMs = istr.readLong();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ArcSpeed v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ArcSpeed ice_read(com.zeroc.Ice.InputStream istr)
    {
        ArcSpeed v = new ArcSpeed();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ArcSpeed> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ArcSpeed v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(36);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<ArcSpeed> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(ArcSpeed.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ArcSpeed _nullMarshalValue = new ArcSpeed();

    /** @hidden */
    public static final long serialVersionUID = 1375268050L;
}
