//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ArcSpeedCalculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MioGraph;

public class GpsEvent implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public int eventType;

    public String date;

    public int stopId;

    public int odometer;

    public double latitude;

    public double longitude;

    public int lineId;

    public int tripId;

    public String datagramDate;

    public int busId;

    public GpsEvent()
    {
        this.date = "";
        this.datagramDate = "";
    }

    public GpsEvent(int eventType, String date, int stopId, int odometer, double latitude, double longitude, int lineId, int tripId, String datagramDate, int busId)
    {
        this.eventType = eventType;
        this.date = date;
        this.stopId = stopId;
        this.odometer = odometer;
        this.latitude = latitude;
        this.longitude = longitude;
        this.lineId = lineId;
        this.tripId = tripId;
        this.datagramDate = datagramDate;
        this.busId = busId;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        GpsEvent r = null;
        if(rhs instanceof GpsEvent)
        {
            r = (GpsEvent)rhs;
        }

        if(r != null)
        {
            if(this.eventType != r.eventType)
            {
                return false;
            }
            if(this.date != r.date)
            {
                if(this.date == null || r.date == null || !this.date.equals(r.date))
                {
                    return false;
                }
            }
            if(this.stopId != r.stopId)
            {
                return false;
            }
            if(this.odometer != r.odometer)
            {
                return false;
            }
            if(this.latitude != r.latitude)
            {
                return false;
            }
            if(this.longitude != r.longitude)
            {
                return false;
            }
            if(this.lineId != r.lineId)
            {
                return false;
            }
            if(this.tripId != r.tripId)
            {
                return false;
            }
            if(this.datagramDate != r.datagramDate)
            {
                if(this.datagramDate == null || r.datagramDate == null || !this.datagramDate.equals(r.datagramDate))
                {
                    return false;
                }
            }
            if(this.busId != r.busId)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::MioGraph::GpsEvent");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, eventType);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, date);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, stopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, odometer);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, latitude);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, longitude);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lineId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, tripId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, datagramDate);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, busId);
        return h_;
    }

    public GpsEvent clone()
    {
        GpsEvent c = null;
        try
        {
            c = (GpsEvent)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.eventType);
        ostr.writeString(this.date);
        ostr.writeInt(this.stopId);
        ostr.writeInt(this.odometer);
        ostr.writeDouble(this.latitude);
        ostr.writeDouble(this.longitude);
        ostr.writeInt(this.lineId);
        ostr.writeInt(this.tripId);
        ostr.writeString(this.datagramDate);
        ostr.writeInt(this.busId);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.eventType = istr.readInt();
        this.date = istr.readString();
        this.stopId = istr.readInt();
        this.odometer = istr.readInt();
        this.latitude = istr.readDouble();
        this.longitude = istr.readDouble();
        this.lineId = istr.readInt();
        this.tripId = istr.readInt();
        this.datagramDate = istr.readString();
        this.busId = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, GpsEvent v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public GpsEvent ice_read(com.zeroc.Ice.InputStream istr)
    {
        GpsEvent v = new GpsEvent();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<GpsEvent> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, GpsEvent v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<GpsEvent> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(GpsEvent.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final GpsEvent _nullMarshalValue = new GpsEvent();

    /** @hidden */
    public static final long serialVersionUID = 1612216200L;
}
