//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ArcSpeedCalculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MioGraph;

/**
 * Helper class for marshaling/unmarshaling GpsEventSeq.
 **/
public final class GpsEventSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, GpsEvent[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                GpsEvent.ice_write(ostr, v[i0]);
            }
        }
    }

    public static GpsEvent[] read(com.zeroc.Ice.InputStream istr)
    {
        final GpsEvent[] v;
        final int len0 = istr.readAndCheckSeqSize(42);
        v = new GpsEvent[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = GpsEvent.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<GpsEvent[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, GpsEvent[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            GpsEventSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<GpsEvent[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            GpsEvent[] v;
            v = GpsEventSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
