//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ArcSpeedCalculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MioGraph;

/**
 * Helper class for marshaling/unmarshaling ProcessingStatsSeq.
 **/
public final class ProcessingStatsSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, ProcessingStats[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                ProcessingStats.ice_write(ostr, v[i0]);
            }
        }
    }

    public static ProcessingStats[] read(com.zeroc.Ice.InputStream istr)
    {
        final ProcessingStats[] v;
        final int len0 = istr.readAndCheckSeqSize(21);
        v = new ProcessingStats[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = ProcessingStats.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ProcessingStats[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, ProcessingStats[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ProcessingStatsSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<ProcessingStats[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            ProcessingStats[] v;
            v = ProcessingStatsSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
