//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ArcSpeedCalculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MioGraph;

public class ProcessingStats implements java.lang.Cloneable,
                                        java.io.Serializable
{
    public int nodeId;

    public int eventsProcessed;

    public int arcsCalculated;

    public long totalTimeMs;

    public String nodeName;

    public ProcessingStats()
    {
        this.nodeName = "";
    }

    public ProcessingStats(int nodeId, int eventsProcessed, int arcsCalculated, long totalTimeMs, String nodeName)
    {
        this.nodeId = nodeId;
        this.eventsProcessed = eventsProcessed;
        this.arcsCalculated = arcsCalculated;
        this.totalTimeMs = totalTimeMs;
        this.nodeName = nodeName;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ProcessingStats r = null;
        if(rhs instanceof ProcessingStats)
        {
            r = (ProcessingStats)rhs;
        }

        if(r != null)
        {
            if(this.nodeId != r.nodeId)
            {
                return false;
            }
            if(this.eventsProcessed != r.eventsProcessed)
            {
                return false;
            }
            if(this.arcsCalculated != r.arcsCalculated)
            {
                return false;
            }
            if(this.totalTimeMs != r.totalTimeMs)
            {
                return false;
            }
            if(this.nodeName != r.nodeName)
            {
                if(this.nodeName == null || r.nodeName == null || !this.nodeName.equals(r.nodeName))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::MioGraph::ProcessingStats");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, nodeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, eventsProcessed);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, arcsCalculated);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalTimeMs);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, nodeName);
        return h_;
    }

    public ProcessingStats clone()
    {
        ProcessingStats c = null;
        try
        {
            c = (ProcessingStats)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.nodeId);
        ostr.writeInt(this.eventsProcessed);
        ostr.writeInt(this.arcsCalculated);
        ostr.writeLong(this.totalTimeMs);
        ostr.writeString(this.nodeName);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.nodeId = istr.readInt();
        this.eventsProcessed = istr.readInt();
        this.arcsCalculated = istr.readInt();
        this.totalTimeMs = istr.readLong();
        this.nodeName = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ProcessingStats v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ProcessingStats ice_read(com.zeroc.Ice.InputStream istr)
    {
        ProcessingStats v = new ProcessingStats();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ProcessingStats> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ProcessingStats v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<ProcessingStats> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(ProcessingStats.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ProcessingStats _nullMarshalValue = new ProcessingStats();

    /** @hidden */
    public static final long serialVersionUID = -1101208268L;
}
