//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ArcSpeedCalculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MioGraph;

public interface SpeedCalculatorWorkerPrx extends com.zeroc.Ice.ObjectPrx
{
    default ArcSpeed[] processEventBatch(GpsEvent[] events, int batchId)
    {
        return processEventBatch(events, batchId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ArcSpeed[] processEventBatch(GpsEvent[] events, int batchId, java.util.Map<String, String> context)
    {
        return _iceI_processEventBatchAsync(events, batchId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ArcSpeed[]> processEventBatchAsync(GpsEvent[] events, int batchId)
    {
        return _iceI_processEventBatchAsync(events, batchId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ArcSpeed[]> processEventBatchAsync(GpsEvent[] events, int batchId, java.util.Map<String, String> context)
    {
        return _iceI_processEventBatchAsync(events, batchId, context, false);
    }

    /**
     * @hidden
     * @param iceP_events -
     * @param iceP_batchId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ArcSpeed[]> _iceI_processEventBatchAsync(GpsEvent[] iceP_events, int iceP_batchId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ArcSpeed[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "processEventBatch", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     GpsEventSeqHelper.write(ostr, iceP_events);
                     ostr.writeInt(iceP_batchId);
                 }, istr -> {
                     ArcSpeed[] ret;
                     ret = ArcSpeedSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default ProcessingStats getStats()
    {
        return getStats(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ProcessingStats getStats(java.util.Map<String, String> context)
    {
        return _iceI_getStatsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ProcessingStats> getStatsAsync()
    {
        return _iceI_getStatsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ProcessingStats> getStatsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getStatsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ProcessingStats> _iceI_getStatsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ProcessingStats> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getStats", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     ProcessingStats ret;
                     ret = ProcessingStats.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void resetStats()
    {
        resetStats(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void resetStats(java.util.Map<String, String> context)
    {
        _iceI_resetStatsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> resetStatsAsync()
    {
        return _iceI_resetStatsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> resetStatsAsync(java.util.Map<String, String> context)
    {
        return _iceI_resetStatsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_resetStatsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "resetStats", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default boolean ping()
    {
        return ping(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean ping(java.util.Map<String, String> context)
    {
        return _iceI_pingAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> pingAsync()
    {
        return _iceI_pingAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> pingAsync(java.util.Map<String, String> context)
    {
        return _iceI_pingAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_pingAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "ping", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SpeedCalculatorWorkerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), SpeedCalculatorWorkerPrx.class, _SpeedCalculatorWorkerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SpeedCalculatorWorkerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), SpeedCalculatorWorkerPrx.class, _SpeedCalculatorWorkerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SpeedCalculatorWorkerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), SpeedCalculatorWorkerPrx.class, _SpeedCalculatorWorkerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SpeedCalculatorWorkerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), SpeedCalculatorWorkerPrx.class, _SpeedCalculatorWorkerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static SpeedCalculatorWorkerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, SpeedCalculatorWorkerPrx.class, _SpeedCalculatorWorkerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static SpeedCalculatorWorkerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, SpeedCalculatorWorkerPrx.class, _SpeedCalculatorWorkerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (SpeedCalculatorWorkerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_adapterId(String newAdapterId)
    {
        return (SpeedCalculatorWorkerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (SpeedCalculatorWorkerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (SpeedCalculatorWorkerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_invocationTimeout(int newTimeout)
    {
        return (SpeedCalculatorWorkerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_connectionCached(boolean newCache)
    {
        return (SpeedCalculatorWorkerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (SpeedCalculatorWorkerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_secure(boolean b)
    {
        return (SpeedCalculatorWorkerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (SpeedCalculatorWorkerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_preferSecure(boolean b)
    {
        return (SpeedCalculatorWorkerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (SpeedCalculatorWorkerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (SpeedCalculatorWorkerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_collocationOptimized(boolean b)
    {
        return (SpeedCalculatorWorkerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_twoway()
    {
        return (SpeedCalculatorWorkerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_oneway()
    {
        return (SpeedCalculatorWorkerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_batchOneway()
    {
        return (SpeedCalculatorWorkerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_datagram()
    {
        return (SpeedCalculatorWorkerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_batchDatagram()
    {
        return (SpeedCalculatorWorkerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_compress(boolean co)
    {
        return (SpeedCalculatorWorkerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_timeout(int t)
    {
        return (SpeedCalculatorWorkerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_connectionId(String connectionId)
    {
        return (SpeedCalculatorWorkerPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default SpeedCalculatorWorkerPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (SpeedCalculatorWorkerPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::MioGraph::SpeedCalculatorWorker";
    }
}
