//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ArcSpeedCalculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MioGraph;

public interface SpeedCalculatorMasterPrx extends com.zeroc.Ice.ObjectPrx
{
    default void registerWorker(String workerProxy, int nodeId)
    {
        registerWorker(workerProxy, nodeId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void registerWorker(String workerProxy, int nodeId, java.util.Map<String, String> context)
    {
        _iceI_registerWorkerAsync(workerProxy, nodeId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> registerWorkerAsync(String workerProxy, int nodeId)
    {
        return _iceI_registerWorkerAsync(workerProxy, nodeId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> registerWorkerAsync(String workerProxy, int nodeId, java.util.Map<String, String> context)
    {
        return _iceI_registerWorkerAsync(workerProxy, nodeId, context, false);
    }

    /**
     * @hidden
     * @param iceP_workerProxy -
     * @param iceP_nodeId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_registerWorkerAsync(String iceP_workerProxy, int iceP_nodeId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerWorker", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_workerProxy);
                     ostr.writeInt(iceP_nodeId);
                 }, null);
        return f;
    }

    default void unregisterWorker(int nodeId)
    {
        unregisterWorker(nodeId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void unregisterWorker(int nodeId, java.util.Map<String, String> context)
    {
        _iceI_unregisterWorkerAsync(nodeId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> unregisterWorkerAsync(int nodeId)
    {
        return _iceI_unregisterWorkerAsync(nodeId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> unregisterWorkerAsync(int nodeId, java.util.Map<String, String> context)
    {
        return _iceI_unregisterWorkerAsync(nodeId, context, false);
    }

    /**
     * @hidden
     * @param iceP_nodeId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_unregisterWorkerAsync(int iceP_nodeId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unregisterWorker", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_nodeId);
                 }, null);
        return f;
    }

    default void processFile(String filePath)
    {
        processFile(filePath, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void processFile(String filePath, java.util.Map<String, String> context)
    {
        _iceI_processFileAsync(filePath, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> processFileAsync(String filePath)
    {
        return _iceI_processFileAsync(filePath, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> processFileAsync(String filePath, java.util.Map<String, String> context)
    {
        return _iceI_processFileAsync(filePath, context, false);
    }

    /**
     * @hidden
     * @param iceP_filePath -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_processFileAsync(String iceP_filePath, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "processFile", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_filePath);
                 }, null);
        return f;
    }

    default ArcSpeed[] getAggregatedResults()
    {
        return getAggregatedResults(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ArcSpeed[] getAggregatedResults(java.util.Map<String, String> context)
    {
        return _iceI_getAggregatedResultsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ArcSpeed[]> getAggregatedResultsAsync()
    {
        return _iceI_getAggregatedResultsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ArcSpeed[]> getAggregatedResultsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getAggregatedResultsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ArcSpeed[]> _iceI_getAggregatedResultsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ArcSpeed[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getAggregatedResults", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     ArcSpeed[] ret;
                     ret = ArcSpeedSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default ProcessingStats[] getAllStats()
    {
        return getAllStats(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ProcessingStats[] getAllStats(java.util.Map<String, String> context)
    {
        return _iceI_getAllStatsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ProcessingStats[]> getAllStatsAsync()
    {
        return _iceI_getAllStatsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ProcessingStats[]> getAllStatsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getAllStatsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ProcessingStats[]> _iceI_getAllStatsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ProcessingStats[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getAllStats", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     ProcessingStats[] ret;
                     ret = ProcessingStatsSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default long getTotalProcessingTime()
    {
        return getTotalProcessingTime(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default long getTotalProcessingTime(java.util.Map<String, String> context)
    {
        return _iceI_getTotalProcessingTimeAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Long> getTotalProcessingTimeAsync()
    {
        return _iceI_getTotalProcessingTimeAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Long> getTotalProcessingTimeAsync(java.util.Map<String, String> context)
    {
        return _iceI_getTotalProcessingTimeAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Long> _iceI_getTotalProcessingTimeAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Long> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getTotalProcessingTime", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     long ret;
                     ret = istr.readLong();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SpeedCalculatorMasterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), SpeedCalculatorMasterPrx.class, _SpeedCalculatorMasterPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SpeedCalculatorMasterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), SpeedCalculatorMasterPrx.class, _SpeedCalculatorMasterPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SpeedCalculatorMasterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), SpeedCalculatorMasterPrx.class, _SpeedCalculatorMasterPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SpeedCalculatorMasterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), SpeedCalculatorMasterPrx.class, _SpeedCalculatorMasterPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static SpeedCalculatorMasterPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, SpeedCalculatorMasterPrx.class, _SpeedCalculatorMasterPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static SpeedCalculatorMasterPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, SpeedCalculatorMasterPrx.class, _SpeedCalculatorMasterPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (SpeedCalculatorMasterPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_adapterId(String newAdapterId)
    {
        return (SpeedCalculatorMasterPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (SpeedCalculatorMasterPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (SpeedCalculatorMasterPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_invocationTimeout(int newTimeout)
    {
        return (SpeedCalculatorMasterPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_connectionCached(boolean newCache)
    {
        return (SpeedCalculatorMasterPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (SpeedCalculatorMasterPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_secure(boolean b)
    {
        return (SpeedCalculatorMasterPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (SpeedCalculatorMasterPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_preferSecure(boolean b)
    {
        return (SpeedCalculatorMasterPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (SpeedCalculatorMasterPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (SpeedCalculatorMasterPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_collocationOptimized(boolean b)
    {
        return (SpeedCalculatorMasterPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_twoway()
    {
        return (SpeedCalculatorMasterPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_oneway()
    {
        return (SpeedCalculatorMasterPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_batchOneway()
    {
        return (SpeedCalculatorMasterPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_datagram()
    {
        return (SpeedCalculatorMasterPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_batchDatagram()
    {
        return (SpeedCalculatorMasterPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_compress(boolean co)
    {
        return (SpeedCalculatorMasterPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_timeout(int t)
    {
        return (SpeedCalculatorMasterPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_connectionId(String connectionId)
    {
        return (SpeedCalculatorMasterPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default SpeedCalculatorMasterPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (SpeedCalculatorMasterPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::MioGraph::SpeedCalculatorMaster";
    }
}
